# Generated by Django 3.1.8 on 2021-04-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contestant_user',
            field=models.BooleanField(default=True),
        ),
    ]
